# Generated by Django 3.1.7 on 2021-04-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('P', 'Pos'), ('N', 'N')], default='P', max_length=200),
        ),
    ]
