# Generated by Django 3.1.7 on 2021-04-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='availablity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='categoty',
            field=models.CharField(blank=True, choices=[('1', 'MOBILE PHONES'), ('2', 'CLOTHINGS'), ('3', 'LAPTOPS'), ('4', 'FOOD')], max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.CharField(choices=[('0', 'NO OFFER'), ('1', '10% OFF WITH CREDIT CARDS'), ('2', 'RS.100 CASHBACK'), ('3', 'FREE SHIPPING')], default='0', max_length=200),
        ),
    ]
