# Generated by Django 3.1.7 on 2021-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210430_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=models.CharField(default='NO OFFER', max_length=200),
        ),
    ]
