# Generated by Django 3.1.7 on 2021-04-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210501_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, db_column='Image', default='1.png', null=True, upload_to='img/'),
        ),
    ]
