# Generated by Django 3.1.7 on 2021-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210501_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(db_column='Image', default='1.png', upload_to='img/'),
        ),
    ]
