# Generated by Django 3.1.7 on 2021-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210502_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Mobile Phone', 'MOBILE PHONE'), ('Clothing', 'CLOTHING'), ('Laptop', 'LAPTOP'), ('Food', 'FOOD')], max_length=100),
        ),
    ]
