# Generated by Django 3.1.7 on 2021-05-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_date_manufactured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='No Warrnaty', max_length=50),
        ),
    ]
