# Generated by Django 3.1.7 on 2021-05-02 10:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=3),
        ),
    ]
